liberal:
  - r/politics
  - r/progressive
  - r/democrats
  - r/environment
  - r/socialism
  - r/DemocraticSocialism
  - r/Enough_Sanders_Spam
  - r/Feminism
  - r/TwoXChromosomes
  - r/LateStageCapitalism
  - r/climate
  - r/Futurology
  - r/WhitePeopleTwitter
  - r/AskALiberal
  - r/Liberal
conservative:
  - r/Conservative
  - r/Republican
  - r/Libertarian
  - r/climateskeptics
  - r/LouderWithCrowder
  - r/JordanPeterson
  - r/Anarcho_Capitalism
  - r/AskThe_Donald
  - r/AskConservatives
  - r/Conservative_News
